### ISSUE TITLE
Cannot vertically resize the recordings list/panel

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#5120] opened 2024-02-08 08:44 UTC
I have a lot of recordings opened... it'd be nice if I could make the `Recordings` listing bigger.

![image](https://github.com/rerun-io/rerun/assets/2910679/b2248715-6568-4e41-8bcb-aecf71664bd9)

**Comment by Wumpf** [comment] 2024-02-15 22:28
* Duplicate of #3421

**Closed by Wumpf** 2024-02-15 22:28 UTC
Labels: enhancement, ui, 📺 re_viewer, 😤 annoying
