### ISSUE TITLE
Selecting an instance containing a batch of keypoint_id + class_id spams a warning: "not a mono-batch"

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6358] opened 2024-05-16 13:24 UTC
Easy repro using the face_tracking example.

```
python -m face_tracking
```
then select any keypoint.

![image](https://github.com/rerun-io/rerun/assets/3312232/cce7b7d3-4af7-4144-a179-758e2c78c659)

Text of the warning:
```
Processing frames: 691it [00:23, 27.51it/s][2024-05-16T13:16:52Z WARN  re_query::latest_at::helpers] Couldn't deserialize /reconstruction/faces/0:rerun.components.ClassId @ TimeInt(690)#17CFFA806598864D24D999916925D29D: not a mono-batch (length: 478)
```

### Root cause

The cause of the problem comes from:
https://github.com/rerun-io/rerun/blob/692b6b6acb185f96d90e0e5a7bf392d6a802d0a3/crates/re_data_ui/src/annotation_context.rs#L97-L99

We are using `latest_at_component` which depends on a mono-component, but the keypoint is an instance of a batch.

To fix this properly, we need to track the instance all the way through EntityDataUi and use it to look up the correct class-id.

### Affects
0.15, 0.16

**Comment by jleibs** [comment] 2024-05-16 13:34
In: https://github.com/rerun-io/rerun/pull/6359 we made this incrementally better by getting rid of the log spam

**Comment by emilk** [comment] 2024-05-16 14:52
Looks like this issue is finally producing real problems:
* https://github.com/rerun-io/rerun/issues/3168

**Comment by emilk** [comment] 2024-05-16 14:53
In fact, I'm closing this as a duplicate of https://github.com/rerun-io/rerun/issues/3168

**Closed by emilk** 2024-05-16 14:53 UTC
Labels: 🪳 bug, ui
