### ISSUE TITLE
Question: Is there an egui compatible Style structure in this project?

### ISSUE THREAD

**Issue by toastxc** [rerun-io/rerun#4718] opened 2024-01-07 14:14 UTC
**Is your feature request related to a problem? Please describe.**

Egui is fantastic and I found that this application is built using it, however this app looks much better than the default Egui styling.

**Describe the solution you'd like**

If possible, I'd love for there to be an accessible package (apart of this repo, on egui, etc) of the `Visuals` or `Style` structure used, so that Egui applications can have a similar look.

**Describe alternatives you've considered**

If this cannot be done, I'd like to know where in this project i can find the styling.

**Additional context**

I've tried out a few rust based GUI libraries (druid, gtk4/adw) and now Egui, I'm fairly new to UI design but enjoying it.

**Comment by emilk** [comment] 2024-01-07 15:12
Duplicate of https://github.com/rerun-io/rerun/issues/3706

The styling is found in the `re_ui` crate!

**Closed by emilk** 2024-01-07 15:12 UTC
Labels: enhancement, 👀 needs triage
