### ISSUE TITLE
Apply Blueprint on specific recording 

### ISSUE THREAD

**Issue by EtaLoop** [rerun-io/rerun#8135] opened 2024-11-14 10:33 UTC
In some cases, I use Blueprint to change background color of a recording view in the viewer.
I would like to specify the recording_id and the application_id in which it should change the background color.

**Comment by EtaLoop** [comment] 2024-11-22 09:21
Hello, I can see that send_blueprint() can take a recording as parameter. That's not the recording_id and application_id but in the end it works the same, no?
https://ref.rerun.io/docs/python/0.20.1/common/initialization_functions/#rerun.send_blueprint

**Comment by teh-cmc** [comment] 2024-12-04 08:18
* Dupe of #8287

**Closed by teh-cmc** 2024-12-04 08:18 UTC
Labels: enhancement, 👀 needs triage
