### ISSUE TITLE
Box label visualization turns off when have >30 boxes

### ISSUE THREAD

**Issue by gauthamnarayan** [rerun-io/rerun#6963] opened 2024-07-23 01:32 UTC
**Describe the bug**
The rerun visualizer seems to turn on box labels when there are lesser than 30 boxes in a scene and then doesn't show the labels when having >30 boxes. This causes the labels to flicker when visualizing datasets with ~30 boxes per frame. I am observing this across multiple datasets when num_boxes > 30.

It would be great to be able to be able to programmatically set when to show the labels. I'm happy to raise a PR if someone can point me in the right direction as well.

**Desktop (please complete the following information):**
Remote server running on Ubuntu 20.04 LTS
Local viewer running on Chrome browser on macOS Sonoma 14.5

**Rerun version**
rerun-cli 0.17.0 [rustc 1.76.0 (07dca489a 2024-02-04), LLVM 17.0.6] x86_64-unknown-linux-gnu release-0.17.0 d65ca50, built 2024-07-08T13:47:55Z
**Additional context**

Scene with 31 boxes. 
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/e0dad0e6-5804-463d-a4c6-da3434fe4687">

Scene with 30 boxes. Everything is same as the above scene, except I deleted one box on the right.
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/b359b3d1-65d6-4a3a-8818-7bfe502130a6">

**Comment by Wumpf** [comment] 2024-07-23 07:34
Thank you for the comprehensive bug report with screenshots and all! However, closing it as a duplicate of this

* https://github.com/rerun-io/rerun/issues/3465

This is the second time within two weeks that someone asks for this, so this should probably be higher prioritized. In the mean time you

**Closed by Wumpf** 2024-07-23 07:34 UTC
Labels: 🪳 bug, 👀 needs triage
