### ISSUE TITLE
Clicking an override component name leads to `Unknown component path` error

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5035] opened 2024-02-05 10:25 UTC
> Unknown component path: /data_query/ffa57c9c-9b7f-4d5d-82e7-3a3ec3eb4c5f/individual_overrides/trig/cos:rerun.components.MarkerShape

The entity path only exists in the blueprint store, but I'm guessing the selection panel looks for it in the recording

![marker-shape-bug](https://github.com/rerun-io/rerun/assets/1148717/865b06bb-a5e3-4a2d-a8e7-b0be16788aa4)

**Comment by teh-cmc** [comment] 2024-02-05 11:07
- Dupe of https://github.com/rerun-io/rerun/issues/4990

**Comment by teh-cmc** [comment] 2024-02-05 11:07
- Dupe of https://github.com/rerun-io/rerun/issues/4990

**Closed by teh-cmc** 2024-02-05 11:07 UTC
Labels: 🪳 bug, 🟦 blueprint
