### ISSUE TITLE
Support numpy2

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6948] opened 2024-07-19 14:13 UTC
Numpy 2.0 has been out for a bit now and is starting to show up as a real dep in more projects.

See: https://numpy.org/devdocs/numpy_2_0_migration_guide.html

Historically we had to limit ourselves to < 2.0 because of:
- https://github.com/PyO3/rust-numpy/issues/409

However, I don't believe we depend on numpy bindings through PyO3 at this point so we may be able to relax our dep.

**Comment by Wumpf** [comment] 2024-07-19 14:34
Duplicate of https://github.com/rerun-io/rerun/issues/6762
Adding the context you wrote here there.

**Closed by Wumpf** 2024-07-19 14:34 UTC
Labels: enhancement, 🐍 Python API, dependencies
