### ISSUE TITLE
Some circumstances lead to tooltip invasion with the web viewer

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#6512] opened 2024-06-06 09:33 UTC
Repro:

https://github.com/rerun-io/rerun/assets/49431240/84dd4569-d3ed-4778-ae7c-aab3695ac0eb

This doesn't seem to happen with the native built.

**Comment by emilk** [comment] 2024-06-10 06:55
If a tooltip contains something that has a tooltip, then we can get into a situation where we get a tooltip for a tooltip for a tooltip… This is not a problem in of itself, but we have some helpful "Open next tooltip quickly" logic that is meant for the situation where you have multiple widgets next to each other and want to quickly inspect their tooltips. That logic means the tooltip of the widget in a tooltip opens right away, causing the problem in the video.

One solution is to never apply that "if a tooltip is already open" logic for widgets in a tooltip layer (`Order::Tooltip`). Another is to only apply it if the open tooltip is in the same `egui::LayerId` as the previous tooltip.

**Comment by emilk** [comment] 2024-06-10 08:18
I fail to reproduce

**Comment by emilk** [comment] 2024-06-10 08:18
I wonder if this is a result of
* https://github.com/rerun-io/rerun/issues/6527

**Comment by emilk** [comment] 2024-06-10 17:17
I'm closing this as a duplicate of https://github.com/rerun-io/rerun/issues/6527

**Closed by emilk** 2024-06-10 17:17 UTC
Labels: 🪳 bug, 🕸️ web, ui, egui
