### ISSUE TITLE
Unclean UI around recording panel

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7197] opened 2024-08-15 08:31 UTC
#7180 introduced several "messy" UI glitches:

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/72162d0d-8af2-4c6d-b8b4-f4b9d7fef251">

This is zoomed in for legibility, but it's clearly visible with the default zoom level.

**Comment by emilk** [comment] 2024-08-16 07:18
The major regression is fixed by https://github.com/rerun-io/rerun/pull/7209

The other problems are pre-existing and is because of this code:

https://github.com/emilk/egui/blob/532c1274610eda6f3088e600c71cb4e5a16b65e2/crates/egui/src/containers/panel.rs#L342-L347

**Closed** 2024-08-16 07:17 UTC
Labels: ui
