### ISSUE TITLE
Viewer spawns new view as tabs when it shouldn't

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3521] opened 2023-09-28 15:00 UTC
https://github.com/rerun-io/rerun/assets/2910679/52905840-d3e1-4b75-a5b8-8fcba8288222

**Comment by emilk** [comment] 2023-09-28 16:11
The problem is that the detection of user-interaction on the `egui_tiles::Tree` is not good enough. It compared the whole tree, but that will include detecting changes due to _simplification_, which we do in of adding a parent tab container to all our view tiles.

This can be fixed by https://github.com/rerun-io/egui_tiles/pull/28 but before I can deploy that I need to wait for a new release of `egui_commonmark`, because `egui_tiles` now depend on egui 0.23…

**Closed** 2023-09-28 17:45 UTC
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression
