### ISSUE TITLE
Codegen should reject archetype fields not marked with `attr.rerun.component_{required|recommended|optional}`

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7442] opened 2024-09-18 17:17 UTC
Currently, codegen happily accept unmarked archetype fields, but then the component is not listed in any of the corresponding `{REQUIRED|RECOMMENDED|OPTIONAL|ALL}_COMPONENTS` lists. When this happen, at least `ViewProperty` will fail to deserialise that component (because it doesn't know about it). Other systems might fail as well.

At a minimum, codegen should fail if any archetype field is not marked with exactly one of these attributes.

**Comment by teh-cmc** [comment] 2024-09-23 11:22
* duplicate of https://github.com/rerun-io/rerun/issues/4739

**Closed by teh-cmc** 2024-09-23 11:22 UTC
Labels: 😤 annoying, codegen/idl
